# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/armaan/Documents/cooperunion/spring_2020/ece453/final/cudaQP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/armaan/Documents/cooperunion/spring_2020/ece453/final/cudaQP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/armaan/Documents/cooperunion/spring_2020/ece453/final/cudaQP/CMakeFiles /home/armaan/Documents/cooperunion/spring_2020/ece453/final/cudaQP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/armaan/Documents/cooperunion/spring_2020/ece453/final/cudaQP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osqp

# Build rule for target.
osqp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqp
.PHONY : osqp

# fast build rule for target.
osqp/fast:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/build
.PHONY : osqp/fast

#=============================================================================
# Target rules for targets named osqpstatic

# Build rule for target.
osqpstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqpstatic
.PHONY : osqpstatic

# fast build rule for target.
osqpstatic/fast:
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/build
.PHONY : osqpstatic/fast

#=============================================================================
# Target rules for targets named osqp_demo

# Build rule for target.
osqp_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqp_demo
.PHONY : osqp_demo

# fast build rule for target.
osqp_demo/fast:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/build
.PHONY : osqp_demo/fast

#=============================================================================
# Target rules for targets named osqp_tester

# Build rule for target.
osqp_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqp_tester
.PHONY : osqp_tester

# fast build rule for target.
osqp_tester/fast:
	$(MAKE) -f CMakeFiles/osqp_tester.dir/build.make CMakeFiles/osqp_tester.dir/build
.PHONY : osqp_tester/fast

#=============================================================================
# Target rules for targets named osqp_algebra

# Build rule for target.
osqp_algebra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqp_algebra
.PHONY : osqp_algebra

# fast build rule for target.
osqp_algebra/fast:
	$(MAKE) -f algebra/CMakeFiles/osqp_algebra.dir/build.make algebra/CMakeFiles/osqp_algebra.dir/build
.PHONY : osqp_algebra/fast

#=============================================================================
# Target rules for targets named kkt_common

# Build rule for target.
kkt_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kkt_common
.PHONY : kkt_common

# fast build rule for target.
kkt_common/fast:
	$(MAKE) -f lin_sys/direct/kkt_common/CMakeFiles/kkt_common.dir/build.make lin_sys/direct/kkt_common/CMakeFiles/kkt_common.dir/build
.PHONY : kkt_common/fast

#=============================================================================
# Target rules for targets named linsys_qdldl

# Build rule for target.
linsys_qdldl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linsys_qdldl
.PHONY : linsys_qdldl

# fast build rule for target.
linsys_qdldl/fast:
	$(MAKE) -f lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/build.make lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/build
.PHONY : linsys_qdldl/fast

#=============================================================================
# Target rules for targets named qdldlstatic

# Build rule for target.
qdldlstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qdldlstatic
.PHONY : qdldlstatic

# fast build rule for target.
qdldlstatic/fast:
	$(MAKE) -f lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlstatic.dir/build.make lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlstatic.dir/build
.PHONY : qdldlstatic/fast

#=============================================================================
# Target rules for targets named qdldl

# Build rule for target.
qdldl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qdldl
.PHONY : qdldl

# fast build rule for target.
qdldl/fast:
	$(MAKE) -f lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl.dir/build.make lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl.dir/build
.PHONY : qdldl/fast

#=============================================================================
# Target rules for targets named qdldl_example

# Build rule for target.
qdldl_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qdldl_example
.PHONY : qdldl_example

# fast build rule for target.
qdldl_example/fast:
	$(MAKE) -f lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl_example.dir/build.make lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldl_example.dir/build
.PHONY : qdldl_example/fast

#=============================================================================
# Target rules for targets named qdldlobject

# Build rule for target.
qdldlobject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qdldlobject
.PHONY : qdldlobject

# fast build rule for target.
qdldlobject/fast:
	$(MAKE) -f lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlobject.dir/build.make lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlobject.dir/build
.PHONY : qdldlobject/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/uninstall.dir/build.make lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

examples/osqp_demo.o: examples/osqp_demo.c.o

.PHONY : examples/osqp_demo.o

# target to build an object file
examples/osqp_demo.c.o:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/examples/osqp_demo.c.o
.PHONY : examples/osqp_demo.c.o

examples/osqp_demo.i: examples/osqp_demo.c.i

.PHONY : examples/osqp_demo.i

# target to preprocess a source file
examples/osqp_demo.c.i:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/examples/osqp_demo.c.i
.PHONY : examples/osqp_demo.c.i

examples/osqp_demo.s: examples/osqp_demo.c.s

.PHONY : examples/osqp_demo.s

# target to generate assembly for a file
examples/osqp_demo.c.s:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/examples/osqp_demo.c.s
.PHONY : examples/osqp_demo.c.s

lin_sys/lib_handler.o: lin_sys/lib_handler.c.o

.PHONY : lin_sys/lib_handler.o

# target to build an object file
lin_sys/lib_handler.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/lin_sys/lib_handler.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/lin_sys/lib_handler.c.o
.PHONY : lin_sys/lib_handler.c.o

lin_sys/lib_handler.i: lin_sys/lib_handler.c.i

.PHONY : lin_sys/lib_handler.i

# target to preprocess a source file
lin_sys/lib_handler.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/lin_sys/lib_handler.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/lin_sys/lib_handler.c.i
.PHONY : lin_sys/lib_handler.c.i

lin_sys/lib_handler.s: lin_sys/lib_handler.c.s

.PHONY : lin_sys/lib_handler.s

# target to generate assembly for a file
lin_sys/lib_handler.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/lin_sys/lib_handler.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/lin_sys/lib_handler.c.s
.PHONY : lin_sys/lib_handler.c.s

src/auxil.o: src/auxil.c.o

.PHONY : src/auxil.o

# target to build an object file
src/auxil.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/auxil.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/auxil.c.o
.PHONY : src/auxil.c.o

src/auxil.i: src/auxil.c.i

.PHONY : src/auxil.i

# target to preprocess a source file
src/auxil.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/auxil.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/auxil.c.i
.PHONY : src/auxil.c.i

src/auxil.s: src/auxil.c.s

.PHONY : src/auxil.s

# target to generate assembly for a file
src/auxil.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/auxil.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/auxil.c.s
.PHONY : src/auxil.c.s

src/ctrlc.o: src/ctrlc.c.o

.PHONY : src/ctrlc.o

# target to build an object file
src/ctrlc.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/ctrlc.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/ctrlc.c.o
.PHONY : src/ctrlc.c.o

src/ctrlc.i: src/ctrlc.c.i

.PHONY : src/ctrlc.i

# target to preprocess a source file
src/ctrlc.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/ctrlc.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/ctrlc.c.i
.PHONY : src/ctrlc.c.i

src/ctrlc.s: src/ctrlc.c.s

.PHONY : src/ctrlc.s

# target to generate assembly for a file
src/ctrlc.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/ctrlc.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/ctrlc.c.s
.PHONY : src/ctrlc.c.s

src/error.o: src/error.c.o

.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/error.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/error.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/error.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/error.c.s
.PHONY : src/error.c.s

src/lin_sys.o: src/lin_sys.c.o

.PHONY : src/lin_sys.o

# target to build an object file
src/lin_sys.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/lin_sys.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/lin_sys.c.o
.PHONY : src/lin_sys.c.o

src/lin_sys.i: src/lin_sys.c.i

.PHONY : src/lin_sys.i

# target to preprocess a source file
src/lin_sys.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/lin_sys.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/lin_sys.c.i
.PHONY : src/lin_sys.c.i

src/lin_sys.s: src/lin_sys.c.s

.PHONY : src/lin_sys.s

# target to generate assembly for a file
src/lin_sys.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/lin_sys.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/lin_sys.c.s
.PHONY : src/lin_sys.c.s

src/osqp_api.o: src/osqp_api.c.o

.PHONY : src/osqp_api.o

# target to build an object file
src/osqp_api.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/osqp_api.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/osqp_api.c.o
.PHONY : src/osqp_api.c.o

src/osqp_api.i: src/osqp_api.c.i

.PHONY : src/osqp_api.i

# target to preprocess a source file
src/osqp_api.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/osqp_api.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/osqp_api.c.i
.PHONY : src/osqp_api.c.i

src/osqp_api.s: src/osqp_api.c.s

.PHONY : src/osqp_api.s

# target to generate assembly for a file
src/osqp_api.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/osqp_api.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/osqp_api.c.s
.PHONY : src/osqp_api.c.s

src/polish.o: src/polish.c.o

.PHONY : src/polish.o

# target to build an object file
src/polish.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/polish.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/polish.c.o
.PHONY : src/polish.c.o

src/polish.i: src/polish.c.i

.PHONY : src/polish.i

# target to preprocess a source file
src/polish.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/polish.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/polish.c.i
.PHONY : src/polish.c.i

src/polish.s: src/polish.c.s

.PHONY : src/polish.s

# target to generate assembly for a file
src/polish.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/polish.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/polish.c.s
.PHONY : src/polish.c.s

src/proj.o: src/proj.c.o

.PHONY : src/proj.o

# target to build an object file
src/proj.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/proj.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/proj.c.o
.PHONY : src/proj.c.o

src/proj.i: src/proj.c.i

.PHONY : src/proj.i

# target to preprocess a source file
src/proj.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/proj.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/proj.c.i
.PHONY : src/proj.c.i

src/proj.s: src/proj.c.s

.PHONY : src/proj.s

# target to generate assembly for a file
src/proj.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/proj.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/proj.c.s
.PHONY : src/proj.c.s

src/scaling.o: src/scaling.c.o

.PHONY : src/scaling.o

# target to build an object file
src/scaling.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/scaling.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/scaling.c.o
.PHONY : src/scaling.c.o

src/scaling.i: src/scaling.c.i

.PHONY : src/scaling.i

# target to preprocess a source file
src/scaling.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/scaling.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/scaling.c.i
.PHONY : src/scaling.c.i

src/scaling.s: src/scaling.c.s

.PHONY : src/scaling.s

# target to generate assembly for a file
src/scaling.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/scaling.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/scaling.c.s
.PHONY : src/scaling.c.s

src/util.o: src/util.c.o

.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/util.c.o
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/util.c.i
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/osqp.dir/build.make CMakeFiles/osqp.dir/src/util.c.s
	$(MAKE) -f CMakeFiles/osqpstatic.dir/build.make CMakeFiles/osqpstatic.dir/src/util.c.s
.PHONY : src/util.c.s

svm/osqp_tester.o: svm/osqp_tester.c.o

.PHONY : svm/osqp_tester.o

# target to build an object file
svm/osqp_tester.c.o:
	$(MAKE) -f CMakeFiles/osqp_tester.dir/build.make CMakeFiles/osqp_tester.dir/svm/osqp_tester.c.o
.PHONY : svm/osqp_tester.c.o

svm/osqp_tester.i: svm/osqp_tester.c.i

.PHONY : svm/osqp_tester.i

# target to preprocess a source file
svm/osqp_tester.c.i:
	$(MAKE) -f CMakeFiles/osqp_tester.dir/build.make CMakeFiles/osqp_tester.dir/svm/osqp_tester.c.i
.PHONY : svm/osqp_tester.c.i

svm/osqp_tester.s: svm/osqp_tester.c.s

.PHONY : svm/osqp_tester.s

# target to generate assembly for a file
svm/osqp_tester.c.s:
	$(MAKE) -f CMakeFiles/osqp_tester.dir/build.make CMakeFiles/osqp_tester.dir/svm/osqp_tester.c.s
.PHONY : svm/osqp_tester.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... osqp"
	@echo "... edit_cache"
	@echo "... osqpstatic"
	@echo "... osqp_demo"
	@echo "... osqp_tester"
	@echo "... rebuild_cache"
	@echo "... osqp_algebra"
	@echo "... kkt_common"
	@echo "... linsys_qdldl"
	@echo "... qdldlstatic"
	@echo "... qdldl"
	@echo "... qdldl_example"
	@echo "... qdldlobject"
	@echo "... uninstall"
	@echo "... examples/osqp_demo.o"
	@echo "... examples/osqp_demo.i"
	@echo "... examples/osqp_demo.s"
	@echo "... lin_sys/lib_handler.o"
	@echo "... lin_sys/lib_handler.i"
	@echo "... lin_sys/lib_handler.s"
	@echo "... src/auxil.o"
	@echo "... src/auxil.i"
	@echo "... src/auxil.s"
	@echo "... src/ctrlc.o"
	@echo "... src/ctrlc.i"
	@echo "... src/ctrlc.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/lin_sys.o"
	@echo "... src/lin_sys.i"
	@echo "... src/lin_sys.s"
	@echo "... src/osqp_api.o"
	@echo "... src/osqp_api.i"
	@echo "... src/osqp_api.s"
	@echo "... src/polish.o"
	@echo "... src/polish.i"
	@echo "... src/polish.s"
	@echo "... src/proj.o"
	@echo "... src/proj.i"
	@echo "... src/proj.s"
	@echo "... src/scaling.o"
	@echo "... src/scaling.i"
	@echo "... src/scaling.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... svm/osqp_tester.o"
	@echo "... svm/osqp_tester.i"
	@echo "... svm/osqp_tester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

